import { Course } from "@/types/course";

export const mockCourses: Course[] = [
    {
        id: "1",
        title: "Content Marketing từ Zero đến Hero",
        description: "Khóa học toàn diện về Content Marketing, từ cơ bản đến nâng cao. Học cách xây dựng chiến lược nội dung, viết content hấp dẫn, và đo lường hiệu quả.",
        instructor: "Nguyễn Văn A",
        instructorAvatar: "https://i.pravatar.cc/150?img=12",
        thumbnail: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=450&fit=crop",
        price: 1990000,
        originalPrice: 2990000,
        rating: 4.8,
        reviewCount: 1250,
        studentCount: 5430,
        duration: "12 giờ",
        level: "Beginner",
        category: "Content Marketing",
        tags: ["Content Strategy", "Copywriting", "SEO"],
        lessons: 48,
        lastUpdated: "Tháng 11, 2024",
        isBestseller: true,
    },
    {
        id: "2",
        title: "SEO Content Writing chuyên nghiệp",
        description: "Nắm vững kỹ thuật viết content chuẩn SEO, tăng traffic tự nhiên cho website. Học từ chuyên gia 10 năm kinh nghiệm.",
        instructor: "Trần Thị B",
        instructorAvatar: "https://i.pravatar.cc/150?img=45",
        thumbnail: "https://images.unsplash.com/photo-1432888498266-38ffec3eaf0a?w=800&h=450&fit=crop",
        price: 1490000,
        originalPrice: 2190000,
        rating: 4.9,
        reviewCount: 890,
        studentCount: 3210,
        duration: "8 giờ",
        level: "Intermediate",
        category: "SEO",
        tags: ["SEO", "Content Writing", "Keywords"],
        lessons: 32,
        lastUpdated: "Tháng 12, 2024",
        isNew: true,
    },
    {
        id: "3",
        title: "Social Media Content Creator",
        description: "Trở thành Content Creator chuyên nghiệp trên các nền tảng mạng xã hội. Học cách tạo nội dung viral, xây dựng thương hiệu cá nhân.",
        instructor: "Lê Văn C",
        instructorAvatar: "https://i.pravatar.cc/150?img=33",
        thumbnail: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=800&h=450&fit=crop",
        price: 1790000,
        originalPrice: 2590000,
        rating: 4.7,
        reviewCount: 1520,
        studentCount: 6780,
        duration: "15 giờ",
        level: "Beginner",
        category: "Social Media",
        tags: ["Social Media", "Video Content", "Branding"],
        lessons: 56,
        lastUpdated: "Tháng 11, 2024",
        isBestseller: true,
    },
    {
        id: "4",
        title: "Video Content Marketing chuyên sâu",
        description: "Làm chủ video marketing từ ý tưởng, kịch bản, quay dựng đến phân phối. Tối ưu hiệu quả với ngân sách hợp lý.",
        instructor: "Phạm Thị D",
        instructorAvatar: "https://i.pravatar.cc/150?img=27",
        thumbnail: "https://images.unsplash.com/photo-1553877522-43269d4ea984?w=800&h=450&fit=crop",
        price: 2290000,
        originalPrice: 3290000,
        rating: 4.9,
        reviewCount: 678,
        studentCount: 2340,
        duration: "18 giờ",
        level: "Advanced",
        category: "Video Marketing",
        tags: ["Video", "YouTube", "TikTok"],
        lessons: 64,
        lastUpdated: "Tháng 10, 2024",
    },
    {
        id: "5",
        title: "Email Marketing & Automation",
        description: "Xây dựng hệ thống email marketing tự động, tăng conversion và giữ chân khách hàng hiệu quả.",
        instructor: "Hoàng Văn E",
        instructorAvatar: "https://i.pravatar.cc/150?img=56",
        thumbnail: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&h=450&fit=crop",
        price: 1290000,
        originalPrice: 1890000,
        rating: 4.6,
        reviewCount: 542,
        studentCount: 1890,
        duration: "10 giờ",
        level: "Intermediate",
        category: "Email Marketing",
        tags: ["Email", "Automation", "CRM"],
        lessons: 40,
        lastUpdated: "Tháng 12, 2024",
        isNew: true,
    },
    {
        id: "6",
        title: "Content Strategy & Planning",
        description: "Học cách xây dựng chiến lược content dài hạn, lập kế hoạch nội dung, và quản lý content calendar chuyên nghiệp.",
        instructor: "Đỗ Thị F",
        instructorAvatar: "https://i.pravatar.cc/150?img=41",
        thumbnail: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=450&fit=crop",
        price: 1690000,
        originalPrice: 2390000,
        rating: 4.8,
        reviewCount: 923,
        studentCount: 4120,
        duration: "14 giờ",
        level: "Intermediate",
        category: "Strategy",
        tags: ["Strategy", "Planning", "Analytics"],
        lessons: 52,
        lastUpdated: "Tháng 11, 2024",
        isBestseller: true,
    },
];
